language: node_js

addons:
  sauce_connect: true

services:
  - mysql

before_install:
  - mysql -uroot -e "CREATE DATABASE jsperf; GRANT ALL ON jsperf.* TO 'jsuser'@'localhost' IDENTIFIED BY 'jspass'; FLUSH PRIVILEGES;"

env:
  - MYSQL_USER=jsuser
  - MYSQL_PASSWORD=jspass
  - MYSQL_DATABASE=jsperf
  - BROWSERSCOPE=encrypt_me_later
  - GITHUB_CLIENT_ID=encrypt_me_later
  - GITHUB_CLIENT_SECRET=encrypt_me_later
  - GITHUB_CALLBACK=http://localhost:3000
  - BELL_COOKIE_PASS=password-should-be-32-characters
  - COOKIE_PASS=password-should-be-32-characters

script:
  - npm test
  - npm start &
  - sleep 3
  - npm run test-e2e

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info || echo "Could not upload code coverage to CodeClimate"
