hub:
  image: selenium/hub:2.46.0
  ports:
    - '4444:4444'

firefox:
  image: selenium/node-firefox:2.46.0
  restart: on-failure
  links:
    - hub
    - lb # from main docker-compose.yml

runner:
  build: .
  dockerfile: Dockerfile-e2e-runner
  environment:
    SELENIUM_REMOTE_URL: http://hub:4444/wd/hub
    JSPERF_REMOTE_URL: http://lb
  links:
    - hub
