web:
  build: .
  restart: always
  env_file: .env
  links:
    - db
    - consul
  expose:
    - '3000'
  environment:
    PORT: 3000
    SERVICE_3000_CHECK_HTTP: '/health'
    SERVICE_3000_CHECK_INTERVAL: '1s'
db:
  image: mysql:5.7
  volumes_from:
    - data-jsperf-mysql
  env_file: .env
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    MYSQL_PASSWORD: $MYSQL_PASSWORD
    MYSQL_DATABASE: jsperf
    MYSQL_USER: jsperf
lb:
  build: ./docker
  dockerfile: Dockerfile-lb
  links:
    - web
    - consul
  ports:
    - '80:80'
consul:
  image: gliderlabs/consul-server:0.6
  command: [-bootstrap, -advertise, 127.0.0.1, -client, 0.0.0.0]
  ports:
   - '8500'
   - '8400:8400'
registrator:
  links:
   - consul
  image: gliderlabs/registrator:v6
  command: -internal consul://consul:8500
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
