FROM gliderlabs/alpine:3.3
RUN echo "@community http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk-install runit@community
RUN echo "http://dl-4.alpinelinux.org/alpine/v3.3/main" >> /etc/apk/repositories && \
    apk add --update nginx=1.8.1-r1 && \
    rm -rf /var/cache/apk/* && \
    chown -R nginx:www-data /var/lib/nginx

RUN apk add --update curl

RUN curl -L -o consul-template.zip https://releases.hashicorp.com/consul-template/0.15.0/consul-template_0.15.0_linux_amd64.zip
RUN unzip consul-template.zip -d /usr/local/bin
RUN rm consul-template.zip

# create default paths for nginx to run
ADD nginx.service /etc/service/nginx/run
ADD consul-template.service /etc/service/consul-template/run
ADD nginx.conf /etc/consul-templates/nginx.conf

CMD ["/sbin/runsvdir", "/etc/service"]
